#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=2
bspc rule -a Steam desktop=0
bspc rule -a Urho3D floating=on
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
